#!/bin/bash
source ~/.virtualenvs/flaskpy3/bin/activate

cd ~/arxiv-sanity-vecs/

python3 arxiv_daemon.py --num 20000

python3 seq_embeddings.py
# Old code to sync databases up to linode after computing features locally:
# rsync data/paper_embeds.p root@172.105.155.181:arxiv-sanity-vecs/data/paper_embeds.p
# rsync data/sentence_features.pt root@172.105.155.181:arxiv-sanity-vecs/data/sentence_features.pt
# rsync data/papers.db root@172.105.155.181:arxiv-sanity-vecs/data/papers.db


rm we_did_it.txt
touch we_did_it.txt
